version: "3.7"
services:

  redis:
    image: redis
    container_name: redis-server
    ports:
      - 6379
    networks:
      - musicbrainz

  db:
    image: cynide/custom-db-musicbrainz
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: musicbrainz
    expose:
      - 5432
    networks:
      - musicbrainz

  server:
    build: .
    volumes:
      - ./musicbrainz-server:/musicbrainz
    links:
      - db
      - redis
    command: bash -c "cd musicbrainz && cpanm --installdeps --notest . && ./script/compile_resources.sh && plackup -Ilib -r"
    environment:
      - REDIS_URL=redis://redis-server
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db

networks:
  musicbrainz:

volumes:
  db-data:
