version: "3.7"
services:

  redis:
    image: redis
    ports:
      - 6379
    networks:
      - musicbrainz

  db:
    image: cynide/custom-db-musicbrainz
    environment:
      POSTGRES_PASSWORD: musicbrainz
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - musicbrainz

  server:
    build: .
    volumes:
      - ./musicbrainz-server:/musicbrainz
    links:
      - db
      - redis
    command: bash -c "cd musicbrainz && cpanm --installdeps --notest . && ./script/compile_resources.sh && ./admin/InitDb.pl --createdb --import /mbdump*.tar.xz --echo && plackup -Ilib -r"
    networks:
      - musicbrainz
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db

networks:
  musicbrainz:
